package.json

Our package is now called `@axa-ch/style-guide`. Deal with it! :laughing:

Use scoped package name

---

docs/less/blocks/highlight.less

This adds a drop shadow to example code as requested by @digisz.
@digisz Please review and merge

Add drop shadow to sample code

---

docs/page/components/snippets/typography.jade
docs/page/components/typography.jade
docs/page/fundamentals/design/icons.jade
less/style.less
less/style/basics.less
less/style/blocks/heading.less
less/style/blocks/paragraph.less
less/style/mixins/font.less

I created mixins for the typography as designed by @anja225.
I'm not really happy with the naming of the mixins. Any input will be appreciated.
- make-font-heading-primary
- make-font-heading-secondary
- make-font-heading-tertiary
- make-font-x-large
- make-font-large
- make-font-large-semibold
- make-font-medium
- make-font-medium-semibold
- make-font-small-semibold
Furthermore I'm not sure whether we need the heading block defined in the style guide. I personally think everybody should use the mixins and we do the same and define headings in the docs.
@davidknezic @sventschui What do you think?

Rework typography

---

less/style/blocks/dropdown.less

Fix dropdown icon on iOS

---

Dockerfile

Dockerize all the things!

---

docs/page/components.jade
docs/page/components/form-and-input-elements.jade
docs/page/components/tables.jade
docs/page/fundamentals.jade
docs/page/inspiration.jade
docs/page/patterns.jade

Well, there is and will never be an left hand side menu on mobile. So I fixed this.

Improve wording on overview pages

---

docs/page/components/snippets/header.jade
docs/page/inspiration/pages/test.jade

Drop the outdated brand__tagline element

Drop tagline

---

docs/page/fundamentals/code/faq.md

Drop code tags in markdown files

---

less/style/blocks/site.less

fixes #401 - separating attributes in css transition.

Bugfix/site  page  mask

---

less/style/blocks/site.less

the expanding/collapsing of the navigation was very stuttering. now it transitions smoothly.

use css transition for mobile menu (better performance)

---

package.json

Fix parsing error by upgrading babelify

---

docs/js/index.js

Svg4everybody was already defined as a dependency, just needed to be instantiated.

Load polyfill for external icons in IE

---

docs/page/fundamentals/code/browser-support.jade

Updated Browser Stats
Removed IE 8 & 9 References, no longer supported

Most epic Change! Updated Statistics

---

docs/page/fundamentals/design/colors.jade

Fix colors page

---

docs/page/components/snippets/typography.jade
less/style/blocks/page-content.less

fixes #477 
I sat down with design and incorporated semantic names.

updated typography names

---

less/style/mixins/respond.less

fixed doubled media queries if large, small, etc is used

---

less/style/mixins/font.less

fixes #488 
ATM i put all variables before the related mixin.
But I consider if it makes more sense to but them inside `variabless.less` file.
What do you guys think?

replaced all hardcoded values by @variables

---

README.md

removed coffee link from readme

---

less/style/blocks/heading.less

Change heading--primary, --secondary, --tertiary color to black

Change heading--primary, --secondary, --tertiary color to black

---

less/style/mixins/make-link.less

Add cursor: pointer to make-link to also show a pointer without href but with JS action

Add cursor: pointer to make-link

---

jquery/info.js

fixed ugly jump

---

docs/js/tab.js

fixed context issues created by arrow functions

---

less/style/blocks/row.less

removed dulpicate properties in .row block

---

.travis.yml

Use node 6.1 in travis build to fix builds

---

package.json

install svg4everybody from npm not via github

---

docs/js/search.js

quckfix with low level throttle

---

tasks/dev.js

fixed wrong method signature

---

docs/page/components/snippets/typography.jade
less/style/blocks/mobile.less
less/style/mixins/font.less

Make the font mixins consistent with the typo pdf
@davidknezic @AndyOGo @anja225 feedback?

Make the font mixins consistent with the typo pdf

---

less/style/blocks/datepicker.less

fixed flex shorthand was set in stack mode of birthday picker

---

tasks/dev.js

update dev task file watch for .js files

updated dev watch for .js files

---

js/jquery/datepicker.js

fixes:
> Uncaught TypeError: _this.moment is not a function

fixed moment should not be overwritten

---

package.json

npm installed babel-register

---

tasks/modernizr.js

I forget to update the scr paths of our custom modernizr build.

updated js src path for modernizr build

---

docs/js/index.js
package.json

fixed `browser` prop is causing some mess

removed browser prop again

---

less/style/blocks/datepicker.less

hardening of .datepicker__trigger__mobile styles

---

js/jquery/autogrow.js

bound context of update method

---

js/jquery/segmented-control.js
less/style/blocks/datepicker.less
less/style/blocks/dropdown.less
less/style/blocks/segmented-control.less
less/style/mixins/ellipsis.less
less/style/mixins/word-break.less

quickly tackles #598 for go live.
This needs to be properly decided and then refactored.

Mobile: Overflow issue in forms

---

js/jquery/modal2.js

quickfix uncaught typeerror of asEventStream is not a function

---

docs/js/search.js

Remove slashes after search once and for all

---

lib/marked-renderer.js

Remove whitespaces in markdown code snippets

---

less/style/blocks/datepicker.less

quickly corrects #612 
Needs proper refactoring.

quicklfix for birthday datepicker max-width

---

docs/layouts/demo.pug
docs/layouts/examples/master.pug
docs/layouts/head.pug
scss/style.scss
scss/style/viewport.scss

Update Viewport meta tag

---

scss/style/blocks/menu-main.scss

reintroduced then menu panel's shadow

---

images/logo.svg
scss/style/blocks/brand.scss

IE11 Logo broken on mobile breakpoint

---

docs/layouts/demo.pug
docs/layouts/inspiration/website.pug
docs/layouts/page.pug
package.json
webpack/bundle.config.babel.js

enable uglify

---

docs/components/snippets/mobile.pug
docs/inspiration/pages/test.pug
docs/layouts/inspiration/website.pug

Just cherry-picked the ul fix of #595

fixed div inside ul

---

README.md
docs/fundamentals/code/faq.md
docs/fundamentals/code/getting-started.pug
docs/fundamentals/code/grid-it-yourself.pug
docs/fundamentals/code/mixins.pug
docs/fundamentals/design/colors.pug

Bugfix/after release v0.16.0

---

js/jquery/datepicker.js
scss/style/blocks/datepicker.scss

Mobile: Open Datepicker through icon does not trigger change

---

scss/style/mixins/word-break.scss

fixing `word-break` being to aggressive in IE

removed word-break as it literally breaks stuff

---

docs/components/form-and-input-elements/radio-buttons.pug

fixed radio button md html not parsed

---

scss/style/blocks/footer-copyline.scss

just fixes a missing ampersand

ooops forgot the ampersand

---

.babelrc
webpack/bundle.dev.config.babel.js

This is just an attempt to fix #686 
Still need to figure out what exactly is going on...
Yeah, just tested this and it's gone. 🎉

moved react-hot-loader from babelrc to webpack dev config

---

webpack/bundle.dev.config.babel.js

ooops, fixed wrong export

---

webpack/bundle.config.babel.js

enable prod build of react

---

lib/createHappyPlugin.js
webpack/bundle.config.babel.js
webpack/bundle.dev.config.babel.js

trying to simplify/streamline webpack config

simplified happy pack creation

---

package.json

`sync-glob` hat bug regarding dirs, which caused our logo to be gone...

updated sync-glob

---

README.md
docs/fundamentals/code/getting-started.pug

removed less relicts

---

lib/build-docs.js

fixed type error

---

scss/style/blocks/button.scss

fixed button tags having borders

---

js/jquery/datepicker-birthday.js

hope that fixes all birthday picker related issues

---

scss/style/mixins/make-column-span.scss

fixed IE flex box basis percentage calculation bug

---

scss/style/mixins/make-column-span.scss

fixed specifity issue

---

scss/style/blocks/icon-teaser.scss

uupps forgot this one

---

scss/style/blocks/icon-teaser.scss

743 Fixed Slick cant calculate correct dimensions for flexed items

---

lib/build-docs.js

745 added missing js state to layouts

---

scss/style/blocks/badge.scss

made badge bullet proof
