docs/js/search.coffee, docs/page/changelog.jade, package.json, tasks/docs-pages.coffee
Lunr has a great feature which filters common words like `but` or `and`. It's a great way to reduce the index size. But strangely it does the same to the search query you type in.
That's why the query `bu` gets you multiple button results, but the query `but` returns an empty list. #296
This PR removes the stop word filter on the client side. It also removes demo pages from the index.
=> Fix stop word behavior in search

docs/config.json, docs/layouts/demo.jade, docs/layouts/examples/master.jade, docs/layouts/page.jade, docs/page/fundamentals/accessibility/basics.jade, docs/page/fundamentals/code/bem.jade, docs/page/fundamentals/code/browser-support.jade, docs/page/fundamentals/code/faq.md, docs/page/fundamentals/code/getting-started.jade, docs/page/fundamentals/design/appicon-and-splashscreen.jade, docs/page/fundamentals/design/colors.jade, docs/page/fundamentals/design/icons.jade, docs/page/fundamentals/layout/devices.jade, docs/page/index.jade, docs/page/patterns/forms.jade, docs/page/patterns/login.jade, docs/page/patterns/spa.jade, lib/marked-renderer-changelog.coffee, lib/marked-renderer.coffee, package.json
This pr fixes all the `Styleguide`, `Design Guide`, `webstyleguide` words and replaces them with `Web Style Guide`. It also makes some improvements to text structure and our Markdown renderers.
=> Fix naming, improve text

tasks/serve.coffee
In order to prevent conflicts with other livereload-powered projects, I upped the default port.
=> Use custom live reload port

docs/layouts/page.jade
Have a look at [Intercom](https://www.intercom.io)'s Acquire module!
It's an amazing way to get and keep in touch with visitors. It's a full messaging experience integrated into the app. Apart from managing ordinary support queries, it also enables us to write to visitors or survey them.
This is what the visitor sees when he starts a new conversation:
Writing to the visitor, without him starting the converation:
List of conversations:
Amazing thing, Intercom has a great mobile app and an even better web app!
=> Introduce Intercom, get rid of UserVoice

less/style/blocks/menu-main.less
This fixes a bug where the menu is too high. Weird is that the style guide docs itself were not affected.
=> Fix menu-main height

package.json, tasks/docs-scripts.coffee, tasks/scripts.coffee
Had this warning message with node `v5`:
```sh
[16:10:21] Parsing file docs/js/index.js: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
```
The problem here, scripts weren't built correctly and broke all our interactivity.
Got rid of it adding the ES2015 preset to babel(ify).
=> Get rid of the sourceType module warning

docs/layouts/page.jade, docs/page/components/snippets/header.jade, docs/page/inspiration/pages/test.jade, less/style.less, less/style/blocks/header.less, less/style/blocks/mobile-actions.less, less/style/variables.less.lodash
The whitespace of the logo spanned the whole empty area in the header. This meant that when you clicked into that white area, you got directed to the homepage. People however aren't used that clicks on empty areas trigger actions, so we needed to get rid of that. Fixes #427
Update @davidknezic:
This is the new markup structure for the mobile actions in the header:
```jade
.header__main__item.header__main__item--mobile-actions.mobile-actions
a.mobile-actions__item(href="#")
+svg('search', ['mobile-actions__icon', 'icon'])
a.mobile-actions__item.site__burger(data-burger, href="#")
svg.mobile-actions__icon.icon.burger-icon(data-burger)
g(stroke="currentColor", stroke-width="2", fill="none", fill-rule="evenodd")
path.burger-icon__top(d="M0,5 L24,5")
path.burger-icon__middle(d="M0,12 L24,12") …
```
=> #427 remove empty clickable area in logo.

docs/page/components/form-and-input-elements/snippets/form-group.jade, jquery/info.coffee, less/style/blocks/info-icon.less
Add a the focus state to our info icon! :tada:
=> Add focus state to info icon

less/style/variables.less.lodash
Suggested by @digisz, this pr improves the bezier animations, so there's no delay at the start of the transition.
=> Improve the bezier animation

less/style/mixins/respond.less
to support writing custom min-width media queries with a less mixin, i propose this addition.
usage:
```
.selector {
height: 5rem;
.respond(30rem, {
height: 10rem;
});
}
```
=> adding a mixin for 'custom' min-width media queries.

.npmignore, less/style/variables.less
We'd like to use the original js sources for our axa.ch build instead of only the compiled ones. That way, we'll be able to include the files using `require('@axa-ch/stye-guide')`. That works, because our `package.json` references `jquery/index.js` as entry point of the package.
Also, in order to resolve the bower issue #439, this pr gets rid of `lodash` in our `less` directory. No precompilation necessary anymore.
=> Leave sources in npm package

.dockerignore, Dockerfile, package.json
So long, no pr. Let's start again!
We're currently facing quite long Docker build times, usually around 10 minutes. That's pretty long compared to the short build times locally.
On my quest to improve that, I made some changes:
... there's still a lot of potential, here's what makes sense next:
... and ultimately there's [these performance problems](https://github.com/npm/npm/issues/8826) with `npm@3` that still don't seem to be resolved.
=> Improve Docker build times

docs/js/index.js, docs/page/components/form-and-input-elements/snippets/textfield-autocomplete.jade, docs/page/components/form-and-input-elements/snippets/textfield-chips.jade, less/style/blocks/chips.less
Fixed the styling of our chips component, so they look like this. No markup is changed.
This fixes #448. Do you think we can merge this @martinoss?
=> Make chips more beautiful

lib/styles.js
fixes #507 
Our CSS-MQ-Packer PostCSS plugin messes up the order (specifity/precendence) of media queries. This cause wrong styles being applied by the browser.
Can be fixed with [MQ-Packer's intrinsic sort feature](https://github.com/hail2u/node-css-mqpacker#sort)
**Example:**
```less
.test {
display:block;
width: 100px;
height: 500px;
background: yellow;
.respond(25rem, {
background: green;
});
.respond(medium, {
background: blue;
});
}
```
**Expected CSS:**
```css
.test {
display:block;
width: 100px;
height: 500px;
background: yellow;
}
@media (min-width: 25rem) {
.test {
background: green;
}
}
@media (min-width: 768px) {
.test {
background: blue;
}
}
```
**Generated CSS:**
```css
.test {
display:block;
width: 100px;
height: 500px;
background: yellow;
}
@media (min-width: 768px) { …
```
=> enabled mqpacker's intrinsic sort feature

less/style/blocks/header-search.less, less/style/blocks/header.less
Only makes sense that the `header-search` block can decide by itself how it wants to look, right? This allows use the block in slightly different locations inside the header 🎉
=> Let the header search set its display & looks

docs/layouts/examples/master.jade, docs/page/components/includes/mixins.jade
Well, if you've seen it, you've probably been pretty confused. But because we had this comment in our mixins file that we included almost everywhere...
```jade
// iOS app icon
mixin appicon_ios(size)
```
... it rendered as an HTML comment, which was included in almost all our snippets 😓.
Could have changed to `//- iOS app icon`, but thought this comment isn't really necessary.
=> Remove silly "iOS app icon" comment from all our snippets

docs/page/components/site.jade, docs/page/components/snippets/site-desktop.jade, docs/page/components/snippets/site-fixed.jade, docs/page/components/snippets/site-left.jade, docs/page/components/snippets/site-stacked.jade, less/style/blocks/site.less, less/style/variables.less
In an attempt to make our side nav more flexible, so we could use this style guide for the Web Guidelines website (yup, you got me right), I'm adding **three modifiers** to the `site` block.
This one flips our side nav to the other side. My recommendation is to adjust the header so the burger is on the left side, too.
The side nav normally pushes the content away. The `stacked` modifier allows you to rather stack over the content.
This one is the one with the biggest impact. It allows you to use the side nav on desktop, too! In order to not break compatibility, the side nav still resides in the `site__mobile` element. I recommend to keep this until we're going to make a bigger release and we're free to rename that one to `site__menu` or something similar.
=> Extend capabilities of the side nav

package.json
fixes #604 
Todo:
**Note** Gulp stuff could skipped, since we are refactoring the whole build w/o gulp
migration guide from jade to pug:
https://pugjs.org/api/migration-v2.html
https://pugjs.org/language/attributes.html#attribute-interpolation
=> Update npm deprecated deps

webpack/bundle.config.babel.js
quickly disabling happypack for css #635 
This needs a proper fix, but since production builds are broken on dev ATM we should quikcly merge this.
=> just disabled happypack for css

docs/mixins.pug
fixes #660 
@davidknezic 
I'm sure the exact same bug exist in the global styleguide too.
=> lowercased icon id in our pug mixin to work with webpack svgstore plugin

scss/style/blocks/footer-copyline.scss
fixes #677 
This is kind of a crazy fix, only needed because of disabled IE 10++ not supporting flex box alignments correctly...
=> only for IE's sake again

webpack/bundle.config.babel.js
fixes #646 
Well I just disabled those warnings, we have eslint anyway and most of them are about vendor stuff, so...
=> disable uglifyjs warnings
